repository:
  # Configurações do repositório
  description: Gerador de documentação OpenAPI para APIs Go
  topics: go, openapi, swagger, documentation, api
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main

  # Proteções da branch principal
  branch_protection:
    main:
      required_status_checks:
        strict: true
        contexts: ['tests', 'linter']
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null 