package generator

import (
	"github.com/jeffemart/gobiru/internal/spec"
)

// Config contém as configurações para geração da documentação
type Config struct {
	OutputFile  string // Caminho do arquivo de saída (opcional, padrão: docs/openapi.json)
	Title       string // Título da API (opcional, padrão: API Documentation)
	Description string // Descrição da API (opcional, padrão: API documentation generated by Gobiru)
	Version     string // Versão da API (opcional, padrão: 1.0.0)
}

// Generator define a interface para geração de documentação
type Generator interface {
	Generate(doc *spec.Documentation, config Config) error
}

// New cria um novo gerador baseado no formato
func New(format string) Generator {
	switch format {
	case "openapi":
		return NewOpenAPIGenerator()
	default:
		return NewOpenAPIGenerator() // Agora OpenAPI é o padrão
	}
}
